config:
  type: aws-parameterstore:/config/caecae/

spring:
  config:
    import: ${config.type}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  s3:
    bucket: ${S3_BUCKET}
  region:
    static: ${REGION}